config/routes.rb
Rails.application.routes.draw do

  root 'maps#test'
  resources :maps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

require 'json'

  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    # @maps = Map.all
    # @maps = Map.find_by_sql("select * from maps")
    @maps = Map.find_by_sql("select id,replace(name,' ','') as name,replace(address,' ','') as address,latitude,longitude,created_at,updated_at from maps")

    # 配列をJsonへ変換する
    @maps_json = @maps.to_json.html_safe

    @arr = ["りんご", "ゴリラ", "ラッパ", "パイナップル"]
    # 配列をJsonへ変換する
    @arr_json = @arr.to_json.html_safe

  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestYMap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>

    <script type="text/javascript" charset="utf-8" src="https://map.yahooapis.jp/js/V1/jsapi?appid=dj00aiZpPTZYSnkwclN5STRpayZzPWNvbnN1bWVyc2VjcmV0Jng9Yjk-"></script>
    <script src="https://unpkg.com/yahoo-map-cluster@latest/bundle/ymap-cluster.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="geocode">

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address , :data => {:target=>"geocode.address"} %>

      <input type="button" value="座標取得" data-action="click->geocode#get_lat_lng">
    </div>



    <div class="field">
      <%= form.label :latitude %>
      <%= form.text_field :latitude , :data => {:target=>"geocode.latitude"}  %>
    </div>

    <div class="field">
      <%= form.label :longitude %>
      <%= form.text_field :longitude , :data => {:target=>"geocode.longitude"}  %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<div data-controller="indexmap">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each_with_index do |map,i| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.address %></td>
        <td data-target="indexmap.latitude" ><%= map.latitude %></td>
        <td data-target="indexmap.longitude" ><%= map.longitude %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td><button data-action = "click->indexmap#move" data-action-index-num = <%= i.to_s %> >Greet</button></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

    <div id="mapwertwerpp" style="width:700px; height:500px"  data-target="indexmap.map" ></div>

</div>

app/views/maps/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<div data-controller="indexmap">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each_with_index do |map,i| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.address %></td>
        <td data-target="indexmap.latitude" ><%= map.latitude %></td>
        <td data-target="indexmap.longitude" ><%= map.longitude %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <td><button data-action = "click->indexmap#move" data-action-index-num = <%= i.to_s %> >Greet</button></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

    <div id="mapwertwerpp" style="width:700px; height:500px"  data-target="indexmap.map" ></div>

</div>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @map.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @map.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @map.longitude %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/maps/test.html.erb
<div data-controller="js-test">
  <div id="bbbb"   data-target="js-test.bbbb"  >
    <input type="button" id="aaaa" value="東京" >
  </div>


  <input type="button" value="書き換え" data-action="click->js-test#change">

</div>




<%= link_to 'Back', maps_path %>

<div data-controller="moving">

  <p>Google Maps APIを使ったサンプルです。</p>

  <div id="mapwertwerpp" style="width:500px; height:300px"  data-target="moving.map" ></div>

  <form>
  <p>
  <input type="button" id="tokyo" value="東京" data-action="click->moving#tokyo">
  <input type="button" id="shinbashi" value="新橋" data-action="click->moving#sinbasi">

  <input type="button" id="shinagawa" value="品川ええ" data-action="click->moving#sinagawa">
  <input type="button" id="shinagawa" value="品川" data-action="click->moving#sinagawa">


  </p>
  </form>

</div>


<!-- <div id="map" style="width:400px; height:300px"></div> -->